<?php

namespace DataBundle\Repository;

/**
 * GabaritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GabaritRepository extends \Doctrine\ORM\EntityRepository
{
}
