<?php

namespace DataBundle\Repository;

/**
 * Service_catRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Service_catRepository extends \Doctrine\ORM\EntityRepository
{
}
